# Generated by Django 2.2.1 on 2019-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMdiagnose', '0002_cases_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='facts',
            field=models.CharField(blank=True, default='nothing', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='reference',
            field=models.CharField(blank=True, default='nothing', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='solution',
            field=models.CharField(blank=True, default='nothing', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='symptom',
            field=models.CharField(blank=True, default='nothing', max_length=2000, null=True),
        ),
    ]
