# Generated by Django 2.2.1 on 2019-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMdiagnose', '0004_yao'),
    ]

    operations = [
        migrations.AddField(
            model_name='yao',
            name='name',
            field=models.CharField(blank=True, default='nothing', max_length=200, null=True),
        ),
    ]
