# Generated by Django 2.2.1 on 2019-07-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMdiagnose', '0005_yao_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='nothing', max_length=200, null=True)),
                ('responses', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
                ('properties', models.CharField(blank=True, default='nothing', max_length=2000, null=True)),
            ],
        ),
    ]
